name: Проверка документации

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        language:
          - "ru"

    steps:
      - name: "Получение php/doc-${{ matrix.language }}"
        uses: "actions/checkout@v4"
        with:
          path: "${{ matrix.language }}"
          repository: "php/doc-${{ matrix.language }}"

      - name: "Получение php/doc-en"
        uses: "actions/checkout@v4"
        with:
          path: "en"
          repository: "php/doc-en"

      - name: "Получение php/doc-base"
        uses: "actions/checkout@v4"
        with:
          path: "doc-base"
          repository: "php/doc-base"

      - name: "Сборка документации для языка ${{ matrix.language }}"
        run: "php8.0 doc-base/configure.php --disable-libxml-check --enable-xml-details --redirect-stderr-to-stdout --with-lang=${{ matrix.language }}"

      - name: "Загрузка .manual.xml"
        uses: actions/upload-artifact@v4
        with:
          name: .manual.xml
          path: doc-base/.manual.xml
