name: Проверка EditorConfig

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: "ubuntu-20.04"
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-lint]')"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Получение изменённых файлов
        id: get_file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ' '
      - name: Запуск editorconfig-checker
        run: npx editorconfig-checker ${{ steps.get_file_changes.outputs.files }}
